# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Builder stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Copy dependencies
COPY package.json package-lock.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.json tsup.config.ts ./

# Install dependencies
RUN npm install

# Copy source
COPY src ./src

# Build project
RUN npx tsup src/index.ts --format esm,cjs --sourcemap --no-dts

# Production stage
FROM node:lts-alpine
WORKDIR /app

# Copy built files and package manifest
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package.json ./package.json

# Install production dependencies
ENV NODE_ENV=production
RUN npm install --only=production

# Use stdio transport entrypoint
ENTRYPOINT ["node", "dist/index.js"]
